ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS notif_push BOOLEAN DEFAULT TRUE;

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS notif_email BOOLEAN DEFAULT TRUE;

ALTER TABLE public.staff
ADD COLUMN IF NOT EXISTS notif_push BOOLEAN DEFAULT TRUE;

ALTER TABLE public.staff
ADD COLUMN IF NOT EXISTS notif_email BOOLEAN DEFAULT TRUE;
