ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS notif_push BOOLEAN DEFAULT TRUE;

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS notif_email BOOLEAN DEFAULT TRUE;

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS notif_security BOOLEAN DEFAULT TRUE;

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS notif_financial BOOLEAN DEFAULT TRUE;

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS notif_budget BOOLEAN DEFAULT TRUE;

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS notif_marketing BOOLEAN DEFAULT FALSE;

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS fcm_token TEXT;

ALTER TABLE public.staff
ADD COLUMN IF NOT EXISTS notif_push BOOLEAN DEFAULT TRUE;

ALTER TABLE public.staff
ADD COLUMN IF NOT EXISTS notif_email BOOLEAN DEFAULT TRUE;

ALTER TABLE public.staff
ADD COLUMN IF NOT EXISTS notif_security BOOLEAN DEFAULT TRUE;

ALTER TABLE public.staff
ADD COLUMN IF NOT EXISTS notif_financial BOOLEAN DEFAULT TRUE;

ALTER TABLE public.staff
ADD COLUMN IF NOT EXISTS notif_budget BOOLEAN DEFAULT TRUE;

ALTER TABLE public.staff
ADD COLUMN IF NOT EXISTS notif_marketing BOOLEAN DEFAULT FALSE;

ALTER TABLE public.staff
ADD COLUMN IF NOT EXISTS fcm_token TEXT;
