import crypto from 'crypto';

export class TransactionSigningService {
    /**
     * Verifies a transaction signature generated by a mobile device's Secure Enclave / Titan M chip.
     */
    verifySecureEnclaveSignature(transactionHash: string, signatureBase64: string, publicKeyPem: string): boolean {
        try {
            const verify = crypto.createVerify('SHA256');
            verify.update(transactionHash);
            verify.end();
            
            const isValid = verify.verify(publicKeyPem, signatureBase64, 'base64');
            console.log(`[SecureEnclave] Transaction signature verification: ${isValid ? 'SUCCESS' : 'FAILED'}`);
            
            return isValid;
        } catch (error: any) {
            console.error(`[SecureEnclave] Verification error: ${error.message}`);
            return false;
        }
    }

    generateTransactionHash(payload: any): string {
        const raw = JSON.stringify(payload);
        return crypto.createHash('sha256').update(raw).digest('hex');
    }
}

export const TransactionSigning = new TransactionSigningService();
