import 'package:orbi_mobileapp/l10n/app_localizations.dart';

class CountryProfile {
  const CountryProfile({
    required this.name,
    required this.code,
    required this.currency,
    required this.dialCode,
    required this.flag,
    required this.nationality,
    required this.languageCode,
    required this.languageLabel,
  });

  final String name;
  final String code;
  final String currency;
  final String dialCode;
  final String flag;
  final String nationality;
  final String languageCode;
  final String languageLabel;
}

const List<CountryProfile> kOrbiCountryProfiles = [
  CountryProfile(
    name: 'Tanzania',
    code: 'TZ',
    currency: 'TZS',
    dialCode: '+255',
    flag: '🇹🇿',
    nationality: 'Tanzanian',
    languageCode: 'sw',
    languageLabel: 'Swahili',
  ),
  CountryProfile(
    name: 'Kenya',
    code: 'KE',
    currency: 'KES',
    dialCode: '+254',
    flag: '🇰🇪',
    nationality: 'Kenyan',
    languageCode: 'sw',
    languageLabel: 'Swahili',
  ),
  CountryProfile(
    name: 'Uganda',
    code: 'UG',
    currency: 'UGX',
    dialCode: '+256',
    flag: '🇺🇬',
    nationality: 'Ugandan',
    languageCode: 'sw',
    languageLabel: 'Swahili',
  ),
  CountryProfile(
    name: 'Rwanda',
    code: 'RW',
    currency: 'RWF',
    dialCode: '+250',
    flag: '🇷🇼',
    nationality: 'Rwandan',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Burundi',
    code: 'BI',
    currency: 'BIF',
    dialCode: '+257',
    flag: '🇧🇮',
    nationality: 'Burundian',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Ghana',
    code: 'GH',
    currency: 'GHS',
    dialCode: '+233',
    flag: '🇬🇭',
    nationality: 'Ghanaian',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Nigeria',
    code: 'NG',
    currency: 'NGN',
    dialCode: '+234',
    flag: '🇳🇬',
    nationality: 'Nigerian',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'South Africa',
    code: 'ZA',
    currency: 'ZAR',
    dialCode: '+27',
    flag: '🇿🇦',
    nationality: 'South African',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Ethiopia',
    code: 'ET',
    currency: 'ETB',
    dialCode: '+251',
    flag: '🇪🇹',
    nationality: 'Ethiopian',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Egypt',
    code: 'EG',
    currency: 'EGP',
    dialCode: '+20',
    flag: '🇪🇬',
    nationality: 'Egyptian',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Morocco',
    code: 'MA',
    currency: 'MAD',
    dialCode: '+212',
    flag: '🇲🇦',
    nationality: 'Moroccan',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Zambia',
    code: 'ZM',
    currency: 'ZMW',
    dialCode: '+260',
    flag: '🇿🇲',
    nationality: 'Zambian',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Botswana',
    code: 'BW',
    currency: 'BWP',
    dialCode: '+267',
    flag: '🇧🇼',
    nationality: 'Motswana',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Zimbabwe',
    code: 'ZW',
    currency: 'ZWL',
    dialCode: '+263',
    flag: '🇿🇼',
    nationality: 'Zimbabwean',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Mozambique',
    code: 'MZ',
    currency: 'MZN',
    dialCode: '+258',
    flag: '🇲🇿',
    nationality: 'Mozambican',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'DR Congo',
    code: 'CD',
    currency: 'CDF',
    dialCode: '+243',
    flag: '🇨🇩',
    nationality: 'Congolese',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Cote d\'Ivoire',
    code: 'CI',
    currency: 'XOF',
    dialCode: '+225',
    flag: '🇨🇮',
    nationality: 'Ivorian',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Senegal',
    code: 'SN',
    currency: 'XOF',
    dialCode: '+221',
    flag: '🇸🇳',
    nationality: 'Senegalese',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Cameroon',
    code: 'CM',
    currency: 'XAF',
    dialCode: '+237',
    flag: '🇨🇲',
    nationality: 'Cameroonian',
    languageCode: 'en',
    languageLabel: 'English',
  ),
  CountryProfile(
    name: 'Angola',
    code: 'AO',
    currency: 'AOA',
    dialCode: '+244',
    flag: '🇦🇴',
    nationality: 'Angolan',
    languageCode: 'en',
    languageLabel: 'English',
  ),
];

List<Map<String, String>> buildOrbiPromoCards(AppLocalizations l10n) => [
  {
    'badge': l10n.onboardingPromo1Badge,
    'title': l10n.onboardingPromo1Title,
    'body': l10n.onboardingPromo1Body,
  },
  {
    'badge': l10n.onboardingPromo2Badge,
    'title': l10n.onboardingPromo2Title,
    'body': l10n.onboardingPromo2Body,
  },
  {
    'badge': l10n.onboardingPromo3Badge,
    'title': l10n.onboardingPromo3Title,
    'body': l10n.onboardingPromo3Body,
  },
  {
    'badge': l10n.onboardingPromo4Badge,
    'title': l10n.onboardingPromo4Title,
    'body': l10n.onboardingPromo4Body,
  },
];

List<String> buildOrbiTermsHighlights(AppLocalizations l10n) => [
  l10n.onboardingTermsHighlight1,
  l10n.onboardingTermsHighlight2,
  l10n.onboardingTermsHighlight3,
  l10n.onboardingTermsHighlight4,
];
